Add backend server
powersync-ja/powersync-react-native-mongodb-mbnb pull request #1
Opened 2024-12-24 07:38 UTC by HeinrichvonStein

These changes add a backend API to the demo app. 

### Future improvements
- Add AuthContext

2024-12-30 20:56 UTC, michaelbarnes requested changes

2024-12-30 20:56 UTC, michaelbarnes commented on README.md
> +tnpm install
@HeinrichvonStein Seems there is a typo here

2024-12-30 20:56 UTC, michaelbarnes commented on README.md
> +npm start
@HeinrichvonStein Please add a `npm install` command above this line.

2024-12-30 20:56 UTC, michaelbarnes commented on backend/package.json
> +  "name": "attendee-list-backend",
Can you change the package name, please?

2024-12-30 20:56 UTC, michaelbarnes commented on backend/tsconfig.json
Can you remove all of the commented out options for the compiler, please?

2024-12-30 21:00 UTC, michaelbarnes commented on README.md
Can we add a small section in the README.md exaplaining that a backend component has been added to the app and that it uses express, Node.js and TypeScript?

2024-12-31 05:43 UTC, HeinrichvonStein commented on README.md
@michaelbarnes I mentioned that in the [beginning](https://github.com/powersync-ja/powersync-react-native-mongodb-mbnb/pull/1/commits/5e50432fccd4345c815598bf555e64815e875192#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R6-R7) of the README. I can extend it if you'd like?

2024-12-31 15:38 UTC, michaelbarnes commented on README.md
> +This repo also contains a Node.js backend API that receives upload from the client.
This repo also contains a Node.js backend API using Express and TypeScript. This API will receive the changes uploaded by the client and will write them back to the MongoDB database. You can run this alongside the frontend project.

2024-12-31 15:39 UTC, michaelbarnes commented on README.md
> +npm start
Swap the cd command and npm install around.

2024-12-31 15:41 UTC, michaelbarnes commented on backend/package.json
> +  "name": "attendee-list-backend",
Change the pnpm references to npm

2024-12-31 17:50 UTC, michaelbarnes approved these changes
LGTM

2024-12-31 17:50 UTC, merged